name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip' # caching pip dependencies
    - name: Pip upgrade
      run: |
        pip install --upgrade pip
    - name: Install flit
      run: |
        pip install flit
    - name: Install dependencies
      run: |
        python -m flit install -s --env --deps=develop --symlink
    - name: Test and coverage
      run: |
        make test
    - name: Format
      run: |
        make format
    - name: Lint
      run: |
        make lint
    - name: Secure
      run: |
        make secure
    - name: Type_check
      run: |
        make type-check
    - name: Coverage Badge
      run: |
        coverage-badge -f -o coverage.svg
